web/router.ex
defmodule Todo.Router do
use Todo.Web, :router

pipeline :browser do
 plug :accepts, ["html"]
 plug :fetch_session
 plug :fetch_flash
 plug :protect_from_forgery
 plug :put_secure_browser_headers
 plug Guardian.Plug.VerifySession
 plug Guardian.Plug.LoadResource
end

pipeline :browser_auth do
 plug Guardian.Plug.VerifySession
 plug Guardian.Plug.EnsureAuthenticated, handler: Todo.Token
 plug Guardian.Plug.LoadResource
end

pipeline :api do
 plug :accepts, ["json"]
end

scope "/", Todo do
 pipe_through :browser # Use the default browser stack

 get "/", PageController, :index
 resources "/users", UserController, only: [:new, :create, :delete]
 resources "/sessions", SessionController, only: [:new, :create, :delete]
end

scope "/", Todo do
 pipe_through [:browser, :browser_auth]
 resources "/users", UserController, only: [:show, :index, :update, :delete]
 resources "/todos", TodoController

  get "/todos/:id/complete_todo", TodoController, :complete_todo
  put "/todos/:id/complete_todo", TodoController, :complete_todo
end


# Other scopes may use custom stacks.
# scope "/api", Todo do
#   pipe_through :api
# end
end

web/views/layout_view.ex
defmodule Todo.LayoutView do
  use Todo.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Todo!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <header class="header">
    <nav role="navigation">
      <ul class="nav nav-pills pull-right">
        <%= render "sign_in_sign_out.html", conn: @conn %><br><br>
      </ul>
    </nav>
    <span class="logo"></span>
  </header>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/sign_in_sign_out.html.eex
<%= if logged_in?(@conn) do %>
  <%= link "Sign out", to: session_path(@conn, :delete, :access),
      method: :delete, class: "btn btn-danger" %><br>
  <%= current_user(@conn).email %>
<% else %>
  <%= link "Create new account", to: user_path(@conn, :new),
      class: "btn btn-danger" %>
  <%= link "Sign in", to: session_path(@conn, :new),
      class: "btn btn-danger" %>
<% end %>